version: '3.9'

services:
  api:
    restart: always
    build: ./server
    container_name: api_container
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'true'

    command:
      - uvicorn main:app
  postgres:
    restart: always
    image: postgres
    container_name: api_db
    environment:
      POSTGRES_USER: postgres